#!/usr/bin/env bash
start_time="$(date -u +%s)"
rm out.txt
for ((i=1;i<=19;i++));
do 
  ./SiftMatcher $1 $PWD/assets/set$i >> out.txt
done

sort -k 3 -g -r out.txt | head -n 5

end_time="$(date -u +%s)"

elapsed="$(($end_time-$start_time))"
echo "Total of $elapsed seconds elap"