########### IMPORTANT #################
######## NOTE ABOUT THIS FILE ########
# We are no longer using whenever gem
# We are using aws cron mechanism
# To avoid any conflicts please refer to https://github.com/tawan/active-elastic-job#set-up-periodic-tasks-cron-jobs
# Please do not edit this file
# Instead go to: app/controllers/background_jobs.rb
# and define any new job there
# once done, open cron.yaml and use it to define the time limit
# 
# 
# Use this file to easily define all of your cron jobs.
#
# It's helpful, but not entirely necessary to understand cron before proceeding.
# http://en.wikipedia.org/wiki/Cron
# Learn more: http://github.com/javan/whenever

#every 3.hours do
#  rake "bookmarks:compose"
#end

#every 1.day, at: '5:00 am' do
#  rake "update_es_cache:perform"
#end