# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: df40f3813dd83d50a9b5e830efead48ff75606b1d87e9d9b1c7acb51e0d78b079ab9b74545d4e5157114fa533c992bbac9bf23f9c52edc0821bc94021684442e
  aws:
    access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
    secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
    region: <%= ENV["AWS_REGION"] %>
    s3_bucket_name: <%= ENV["S3_BUCKET_NAME"] %>
  elasticsearch:
    host: <%= ENV["ELASTICSEARCH_HOST"] %>
    user: <%= ENV["ELASTICSEARCH_USER"] %>
    password: <%= ENV["ELASTICSEARCH_PASSWORD"] %>
    port: <%= ENV["ELASTICSEARCH_PORT"] %>
  silverpop_config:
    key: <%= ENV['SP_KEY'] %>
    secret: <%= ENV['SP_SECRET'] %>
    refresh: <%= ENV['SP_REFRESH_TOKEN'] %>
    endpoint: <%= ENV['SP_HOST'] %>
    list_id: <%= ENV['SP_LIST_ID'] %>

test:
  secret_key_base: df5c10bf3c2152776221fe97f4c7ffec94cfc8344b96fd0a8eff468c4702b9c3baf42a15c1ce77ee6e189d5339e4d8778deec21d16d93a69ffa933c08aa4d4c2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws:
    access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
    secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
    region: <%= ENV["AWS_REGION"] %>
    s3_bucket_name: <%= ENV["S3_BUCKET_NAME"] %>
  elasticsearch:
    host: <%= ENV["ELASTICSEARCH_HOST"] %>
    user: <%= ENV["ELASTICSEARCH_USER"] %>
    password: <%= ENV["ELASTICSEARCH_PASSWORD"] %>
    port: <%= ENV["ELASTICSEARCH_PORT"] %>
  silverpop_config:
    refresh: <%= ENV['SP_REFRESH_TOKEN'] %>
    secret: <%= ENV['SP_SECRET'] %>
    key: <%= ENV['SP_KEY'] %>
    list_id: <%= ENV['SP_LIST_ID'] %>
    endpoint: <%= ENV['SP_HOST'] %>
  sendgrid:
    user_name: <%= ENV["SENDGRID_USERNAME"] %>
    password: <%= ENV["SENDGRID_PASSWORD"] %>
    domain: <%= ENV["SENDGRID_DOMAIN"] %>
    address: <%= ENV["SENDGRID_ADDRESS"] %>